/**
 * DataRiver Telegraph
 *
 * Config for Telegraph
 */

module.exports = {
    SendGridUser: 'grgortiz',
    SendGridPass: '3ataRiver!',
    emailFrom: 'mromney@equationhealth.com',
    emailFromName: 'Mike Romney - Equation',
    emailSubject: 'Webinar: Analyzing Data Across Service Lines',
    emailText: "Are you like most hospital executives?\r\n\r\nYou lack the ability to drill down into consolidated hospital and physician financial statements to get to the transactional level details you require for strategic service line decisions.\r\n\r\nWe can show you how!\r\n\r\nDataRiver Service Line Analyzer is a web-based tool that enables you to drill down into your hospital inpatient, outpatient, and physician practice data to achieve improvements in alignment, profitability and cost of care within your service lines.\r\n\r\nJoin us for a webinar:\r\n\r\n* Date: June 17th\r\n\r\n* Time: 1:00 PM EST\r\n\r\n* Subject: Analyzing Consolidated Hospital and Physician Practice Data Across Service Lines\r\n\r\nHere's what a CFO from an Ohio health system said about Service Line Analyzer:\r\n\r\n\"Service Line Analyzer gives me direct, easy access to my hospital's data. Now I have a direct view into the performance of individual service lines and can confidently identify expansion opportunities as well as the need for divestiture. It’s given me the data visibility I’ve been looking for.\"\r\n\r\nClick on the link below to sign-up for the webinar.\r\n\r\nhttp://go.equationhealth.com/service-line-analyzer-webinar/\r\n\r\nIf you are unable to attend, please sign up anyway and we will send you copy of the presentation.\r\n\r\nWe look forward to hearing from you.\r\n\r\n-----------------------------------------------\r\n\r\nMike Romney\r\n\r\nVice President of Business Development, Equation\r\n\r\nmromney@equationhealth.com\r\n\r\n801.783.4100\r\n\r\nwww.equationhealth.com",
    // Intro to Equation
    // emailText: "As a healthcare professional, have you ever asked yourself questions like these?\r\n\r\n* How do I discover specific inefficiencies within a practice that I know is struggling in performance?\r\n\r\n* How can I compare the profitability of specific service lines in order to plan for future growth?\r\n\r\n* How can I determine the true financial value of a particular physician practice?\r\n\r\n* How can I identify and target potential markets for expansion?\r\n\r\nThe answers lie deep within your health system’s data. But how can you easily drill down into your data to find the answers and gain the data liberation for which you've been yearning?\r\n\r\nEquation can help! Our business intelligence (BI), data modeling, and analytics capabilities provide answers to your questions.\r\n\r\nOur analytic tools will assist you in positively aligning your system’s economic and organizational strategy. The tools provide easy access to your data in the form of web-based charts, reports, and dashboards. You can choose how you view your data.\r\n\r\nEquation’s BI platform, DataRiver, includes:\r\n\r\n* Physician Analyzer - Comprehensive reporting that covers key productivity, revenue and cost drivers for your physicians. Easily assess visit coding, payer mix, physician compensation and more.\r\n\r\n* Service Line Analyzer - Drill down into consolidated inpatient, outpatient, and physician practice data to achieve improvements in quality and productivity within your service lines across departments.\r\n\r\n* Downstream Analyzer - Easily determine the downstream value of an employed physician across your health system. Consolidate hospital & physician data to see the total value provided by a physician.\r\n\r\n* Market Analyzer - Obtain deep visibility into your market’s data.  Drill down into one standardized data model to look at specific data elements across any market.\r\n\r\nTo learn more or request a call, visit:\r\n\r\nhttp://go.equationhealth.com/healthcare-analytics/?utm_source=telegraph&utm_medium=email&utm_campaign=intro\r\n\r\nYou provide the questions. Equation provides the answers.\r\n\r\nContact us. We’d love to discuss our healthcare solutions with you.\r\n\r\n-----------------------------------------------\r\n\r\nMike Romney, VP Business Development\r\n\r\nEquation\r\n\r\nmromney@equationhealth.com\r\n\r\n801.783-4100\r\n\r\nwww.equationhealth.com",
    emailHtml: ''
}